# Generated by Django 6.0.2 on 2026-05-04 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exchange_book_received_an_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='duration',
        ),
        migrations.AddField(
            model_name='exchange',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 9, 50, 43, 288378)),
            preserve_default=False,
        ),
    ]
